### ISSUE TITLE
cntr from old matplotlib used in the vispy

### ISSUE THREAD

**Issue by chongxi** [chongxi/spiketag#51]
```python
Traceback (most recent call last):
  File "/disk0/Work/pydev/vispy/examples/demo/scene/flow_lines.py", line 13, in <module>
    from vispy import app, scene, visuals, gloo
  File "/disk0/Work/pydev/vispy/vispy/scene/__init__.py", line 33, in <module>
    from .visuals import *  # noqa
  File "/disk0/Work/pydev/vispy/vispy/scene/visuals.py", line 18, in <module>
    from .. import visuals
  File "/disk0/Work/pydev/vispy/vispy/visuals/__init__.py", line 22, in <module>
    from .isocurve import IsocurveVisual  # noqa
  File "/disk0/Work/pydev/vispy/vispy/visuals/isocurve.py", line 18, in <module>
    from matplotlib import _cntr as cntr
ImportError: cannot import name '_cntr' from 'matplotlib' (/disk0/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py)
```

**Comment by chongxi** [comment]
conda list | grep matplotlib
matplotlib                3.1.0            py37h5429711_0

**Comment by chongxi** [comment]
Solved in https://github.com/chongxi/vispy/commit/70497b25de91be121b1b2e3ce1e280d408910189
